# include ../../Makefile.inc

# SOURCES=$(wildcard *.c)
# SOURCES_COMMANDS=$(wildcard prompt_commands/*.c)
# OBJECTS=$(SOURCES:.c=.o)
# OBJECTS_COMMANDS=$(SOURCES_COMMANDS:.c=.o)

# ALL_OBJECTS= $(OBJECTS) $(OBJECTS_COMMANDS)

# STATICLIBS=

# all: $(OBJECTS)

# %.o:%.c
# 	$(GCC) $(GCCFLAGS) -I./include -c $< -o $@

# clean:
# 	rm -rf *.o

# .PHONY: all clean print